assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angela Upreti
email: aupreti at umass dot edu
description: >- # this means to ignore newlines until "baseurl:"
  Angela Upreti's website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aupreti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  aupreti
linkedin_username: angelaupreti

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-123789608-1

header_pages:
  - about.md
  - blog.md
  - personal.md
  - gallery.md

gems:
    - jekyll-maps

maps:
    google:
      api_key: AIzaSyBX67uzcQutGa4Uv9MmLzSY0dvXTapGOyU
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock


plugins:
  - jekyll-assets
  - jekyll-sitemap

name:

permalink: pretty
